stages:
  - build
  - test

build:
  stage: build
  script:
    - echo "Building the project..."
    - mvn clean install
  artifacts:
    paths:
      - target/

test:
  stage: test
  script:
    - echo "Running tests and redirecting Surefire reports..."
    - mvn test -Dsurefire.reportDirectory=target/custom-surefire-reports
  artifacts:
    paths:
      - target/custom-surefire-reports/
  reports:
    junit:
      - target/custom-surefire-reports/*.xml
