name: Build and Deploy to Render

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Build Docker image
        run: docker build . --file Dockerfile --tag xalmon/logapp:latest

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker image to Docker Hub
        run: docker push xalmon/logapp:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Render
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
        run: |
          docker pull xalmon/logapp:latest
          docker tag xalmon/logapp:latest registry.render.com/${{ secrets.RENDER_SERVICE_ID }}:latest
          docker push registry.render.com/${{ secrets.RENDER_SERVICE_ID }}:latest

          curl -X POST \
            -H "Authorization: Bearer $RENDER_API_KEY" \
            -H "Content-Type: application/json" \
            -d '{"serviceId": "'$RENDER_SERVICE_ID'", "command": "docker run"}' \
            https://api.render.com/v1/services/${RENDER_SERVICE_ID}/deploys
